#!/bin/bash

set -x
yum update -y

yum install git -y

which git

git --version
git config --global user.name 'noshad'
git config --global user.email 'noshadmalik98@gmail.com'
git config --list
mkdir git
cd git
git init
touch gitfile
#put some date into this file
git status
git add .
git commit -m '1st commit'
git status
git log
git log -1
git log -2
git log --onelone
git log --grep 'ignore'
